if(new URLSearchParams(location.search).has('export'))document.documentElement.classList.add('export');
const index=document.querySelector('.index'), toggle=document.querySelector('.index-toggle');
function showIndex(open){index.hidden=!open;toggle.setAttribute('aria-expanded',String(open));if(open)index.querySelector('a').focus();else toggle.focus();}
toggle.addEventListener('click',()=>showIndex(index.hidden));document.querySelector('.index-close').addEventListener('click',()=>showIndex(false));
index.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{index.hidden=true;toggle.setAttribute('aria-expanded','false')}));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!index.hidden)showIndex(false)});
document.addEventListener('click',e=>{if(!index.hidden&&!index.contains(e.target)&&!toggle.contains(e.target)){index.hidden=true;toggle.setAttribute('aria-expanded','false')}});
const bar=document.querySelector('.progress');let scheduled=false;function progress(){bar.style.width=(scrollY/(document.documentElement.scrollHeight-innerHeight)*100)+'%';scheduled=false}window.addEventListener('scroll',()=>{if(!scheduled){scheduled=true;requestAnimationFrame(progress)}},{passive:true});progress();
const track=document.querySelector('.study-track');document.querySelector('.study-next').addEventListener('click',()=>track.scrollBy({left:track.firstElementChild.clientWidth+26,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));document.querySelector('.study-prev').addEventListener('click',()=>track.scrollBy({left:-track.firstElementChild.clientWidth-26,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'}));
const craft=document.querySelector('.craft-image'), note=document.querySelector('.craft-note');craft.addEventListener('click',()=>{note.hidden=!note.hidden;craft.setAttribute('aria-expanded',String(!note.hidden));craft.querySelector('.image-tag span').textContent=note.hidden?'＋':'−'});
const looks=[{title:'Heritage',copy:'Craft takes centre stage. The cloth is wrapped and draped, letting its woven edge guide the silhouette.',alt:'Heritage interpretation of the scarlet textile, draped with an ivory woven border'},{title:'Contemporary',copy:'Traditional material meets modern tailoring. A precise trouser suit gives the same woven cloth an entirely different rhythm.',alt:'Contemporary interpretation of the same scarlet textile, tailored into a trouser suit'},{title:'Experimental',copy:'Proportion, layering and unexpected construction transform familiar material. The cloth becomes a sculptural volume.',alt:'Experimental interpretation of the same scarlet textile in a sculptural asymmetric silhouette'}];
const tabs=[...document.querySelectorAll('[role=tab]')];function selectLook(i){tabs.forEach((t,n)=>{t.setAttribute('aria-selected',String(n===i));t.tabIndex=n===i?0:-1});document.querySelector('#look-image').style.left=(-i*100)+'%';document.querySelector('#look-image').alt=looks[i].alt;document.querySelector('#look-title').textContent=looks[i].title;document.querySelector('#look-copy').textContent=looks[i].copy;document.querySelector('.look-number').textContent='0'+(i+1);document.querySelector('#look-panel').setAttribute('aria-labelledby',tabs[i].id)}tabs.forEach((t,i)=>{t.addEventListener('click',()=>selectLook(i));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%3;if(e.key==='ArrowLeft')n=(i+2)%3;if(e.key==='Home')n=0;if(e.key==='End')n=2;if(n!==undefined){e.preventDefault();selectLook(n);tabs[n].focus()}})});
if(!document.documentElement.classList.contains('export')&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('arriving');observer.unobserve(e.target)}}),{threshold:.15});document.querySelectorAll('.story figure,.editor-image,.future-layout figure').forEach(el=>observer.observe(el));const paths=[...document.querySelectorAll('.thread path')].map(path=>({path,length:path.getTotalLength()}));paths.forEach(({path,length})=>{path.style.strokeDasharray=length;path.style.strokeDashoffset=length});function drawThreads(){paths.forEach(({path,length})=>{const r=path.parentElement.getBoundingClientRect(),fraction=Math.max(0,Math.min(1,(innerHeight-r.top)/(innerHeight+r.height)));path.style.strokeDashoffset=length*(1-fraction)})}window.addEventListener('scroll',drawThreads,{passive:true});drawThreads()}
